# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0003_auto_20160824_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='tarefa_data_inico',
            new_name='tarefa_data_inicio',
        ),
    ]
